# Generated by Django 5.2.7 on 2025-10-23 14:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datos_personales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoCupoLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Estado Acompañamiento Cupo Laboral')),
            ],
            options={
                'verbose_name': 'Estado Cupo Laboral',
                'verbose_name_plural': 'Estados Cupo Laboral',
            },
        ),
        migrations.CreateModel(
            name='NivelEndeudamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nivel de Endeudamiento')),
            ],
            options={
                'verbose_name': 'Nivel de Endeudamiento',
                'verbose_name_plural': 'Niveles de Endeudamiento',
            },
        ),
        migrations.CreateModel(
            name='OpcionSINO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Opción Sí/No/Temporalmente No')),
            ],
            options={
                'verbose_name': 'Opción Sí/No',
                'verbose_name_plural': 'Opciones Sí/No',
            },
        ),
        migrations.CreateModel(
            name='SituacionLaboralPrincipal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Situación Laboral Principal')),
            ],
            options={
                'verbose_name': 'Situación Laboral Principal',
                'verbose_name_plural': 'Situaciones Laborales Principales',
            },
        ),
        migrations.CreateModel(
            name='TipoAcompanamientoLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Tipo de Acompañamiento Laboral')),
            ],
            options={
                'verbose_name': 'Tipo de Acompañamiento Laboral',
                'verbose_name_plural': 'Tipos de Acompañamiento Laboral',
            },
        ),
        migrations.CreateModel(
            name='AcompanamientoLaboral',
            fields=[
                ('persona', models.OneToOneField(help_text='Un registro laboral por cada persona.', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='datos_personales.persona', verbose_name='Persona Acompañada')),
                ('ingreso_economico_promedio', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ingreso Económico Promedio Mensual ($)')),
                ('antiguedad_laboral_meses', models.IntegerField(blank=True, help_text='Mide la estabilidad de la fuente de ingresos.', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Antigüedad en la Situación Laboral (Meses)')),
                ('posee_cv', models.CharField(blank=True, help_text='Opciones (Sí/No, ¿De quién/Qué?)', max_length=255, null=True, verbose_name='CV (Currículum Vitae)')),
                ('acceso_a_prestaciones', models.TextField(blank=True, help_text='Listado (Ej: Potenciar Trabajo, Pensiones No Contributivas, otros subsidios)', verbose_name='Acceso a Prestaciones/Ayudas')),
                ('dependencia_economica', models.CharField(blank=True, help_text='Opciones (Sí/No, ¿De quién/Qué?). Mide el grado de autonomía.', max_length=255, null=True, verbose_name='Dependencia Económica')),
                ('acompanamiento_cupo_laboral', models.ForeignKey(blank=True, help_text='Seguimiento específico de la política pública.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='InsercionLaboral.estadocupolaboral', verbose_name='Acompañamiento para Cupo Laboral')),
                ('nivel_endeudamiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='InsercionLaboral.nivelendeudamiento', verbose_name='Nivel de Endeudamiento')),
                ('interes_empleo_formal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interes_formal', to='InsercionLaboral.opcionsino', verbose_name='Interés en Empleo Formal')),
                ('situacion_laboral_principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='InsercionLaboral.situacionlaboralprincipal', verbose_name='Situación Laboral Principal')),
                ('tipo_acompanamiento_laboral', models.ManyToManyField(blank=True, help_text='Selección Múltiple (Armado de CV, Simulación de entrevista, etc.)', to='InsercionLaboral.tipoacompanamientolaboral', verbose_name='Tipo de Acompañamiento Laboral')),
            ],
            options={
                'verbose_name': 'Acompañamiento - Laboral y Economía',
                'verbose_name_plural': 'Acompañamiento - Inserción Laboral y Autonomía Económica',
            },
        ),
    ]
