# Generated by Django 5.2.7 on 2025-10-23 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datos_personales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotivoCierre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Motivo de Cierre')),
            ],
            options={
                'verbose_name': 'Motivo de Cierre de Caso',
                'verbose_name_plural': 'Motivos de Cierre de Caso',
            },
        ),
        migrations.CreateModel(
            name='NivelRiesgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nivel de Riesgo')),
            ],
            options={
                'verbose_name': 'Nivel de Riesgo',
                'verbose_name_plural': 'Niveles de Riesgo',
            },
        ),
        migrations.CreateModel(
            name='TipoIntervencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Tipo de Intervención')),
            ],
            options={
                'verbose_name': 'Tipo de Intervención',
                'verbose_name_plural': 'Tipos de Intervención',
            },
        ),
        migrations.CreateModel(
            name='PlanIntervencion',
            fields=[
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='datos_personales.persona', verbose_name='Persona Acompañada')),
                ('objetivo_general_caso', models.TextField(verbose_name='Objetivo General del Caso (Meta a largo plazo)')),
                ('fecha_cierre', models.DateField(blank=True, null=True, verbose_name='Fecha de Cierre')),
                ('evaluacion_final_resultados', models.TextField(blank=True, help_text='Impacto de la intervención en la calidad de vida y derechos.', verbose_name='Evaluación Final de Resultados')),
                ('motivo_cierre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='PlanSeguimiento.motivocierre', verbose_name='Motivo de Cierre')),
            ],
            options={
                'verbose_name': 'Plan de Intervención',
                'verbose_name_plural': 'Planes de Intervención y Cierre',
            },
        ),
        migrations.CreateModel(
            name='RegistroSeguimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_contacto', models.DateField(verbose_name='Fecha del Contacto/Intervención')),
                ('acciones_por_eje', models.TextField(blank=True, help_text='Listado de tareas y objetivos a corto/medio plazo.', verbose_name='Acciones por Eje (Salud, Empleo, Documentación, Educación)')),
                ('plazo_estimado_accion', models.CharField(blank=True, help_text='Fecha o Indicación Temporal (Ej: 3 meses).', max_length=100, verbose_name='Plazo Estimado por Acción')),
                ('resumen_avances_obstaculos', models.TextField(help_text='Registro narrativo breve y profesional.', verbose_name='Resumen de Avances y Obstáculos')),
                ('derivaciones_realizadas', models.TextField(blank=True, help_text='Institución, Fecha y Contacto.', verbose_name='Derivaciones Realizadas')),
                ('nivel_riesgo_actual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='PlanSeguimiento.nivelriesgo', verbose_name='Nivel de Riesgo Actual del Caso')),
                ('plan_intervencion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_seguimiento', to='PlanSeguimiento.planintervencion', verbose_name='Plan de Intervención Asociado')),
                ('tipo_intervencion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='PlanSeguimiento.tipointervencion', verbose_name='Tipo de Intervención')),
            ],
            options={
                'verbose_name': 'Registro de Seguimiento',
                'verbose_name_plural': 'Registros de Seguimiento',
                'ordering': ['-fecha_contacto'],
            },
        ),
    ]
