# Generated by Django 5.2.7 on 2025-10-23 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datos_personales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccesoSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Acceso al Sistema de Salud')),
            ],
            options={
                'verbose_name': 'Acceso a Sistema de Salud',
                'verbose_name_plural': 'Accesos a Sistema de Salud',
            },
        ),
        migrations.CreateModel(
            name='BarreraSalud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Barrera Sanitaria o Psicosocial')),
            ],
            options={
                'verbose_name': 'Barrera de Salud',
                'verbose_name_plural': 'Barreras de Salud',
            },
        ),
        migrations.CreateModel(
            name='EstadoSalud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Estado de Salud (Percibido)')),
            ],
            options={
                'verbose_name': 'Estado de Salud',
                'verbose_name_plural': 'Estados de Salud',
            },
        ),
        migrations.CreateModel(
            name='TipoTerapia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Tipo de Acompañamiento Terapéutico')),
            ],
            options={
                'verbose_name': 'Tipo de Terapia',
                'verbose_name_plural': 'Tipos de Terapia',
            },
        ),
        migrations.CreateModel(
            name='AcompanamientoSalud',
            fields=[
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='datos_personales.persona', verbose_name='Persona Acompañada')),
                ('medicacion_cronica', models.TextField(blank=True, help_text='Listar medicamentos, dosis y diagnóstico asociado.', verbose_name='Medicación Crónica Actual')),
                ('requiere_terapia', models.BooleanField(default=False, verbose_name='Requiere Acompañamiento Psicológico/Psiquiátrico')),
                ('consumo_sustancias', models.CharField(blank=True, help_text='Especificar tipo y frecuencia si la respuesta es Sí.', max_length=255, verbose_name='Consumo de Sustancias/Tóxicos')),
                ('notas_bienestar', models.TextField(blank=True, help_text='Observaciones, red de apoyo, situaciones de crisis.', verbose_name='Notas de Bienestar Psicosocial')),
                ('acceso_sistema_salud', models.ForeignKey(blank=True, help_text='Ej: Público, Privado, Obras Sociales.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='SaludIntegral.accesosistema', verbose_name='Acceso al Sistema de Salud')),
                ('barreras_salud', models.ManyToManyField(blank=True, help_text='Identifica obstáculos para el acceso (Ej: Discriminación en consultorio, Falta de insumos).', to='SaludIntegral.barrerasalud', verbose_name='Barreras Sanitarias y Psicosociales')),
                ('estado_salud_general', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='SaludIntegral.estadosalud', verbose_name='Estado de Salud General (Percibido)')),
                ('tipo_terapia_actual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='SaludIntegral.tipoterapia', verbose_name='Tipo de Terapia Actual (si aplica)')),
            ],
            options={
                'verbose_name': 'Acompañamiento - Salud',
                'verbose_name_plural': 'Acompañamiento - Salud Integral y Bienestar',
            },
        ),
    ]
