# Generated by Django 5.2.7 on 2025-10-23 14:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoDNI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Estado DNI Rectificado')),
            ],
            options={
                'verbose_name': 'Estado DNI',
                'verbose_name_plural': 'Estados DNI',
            },
        ),
        migrations.CreateModel(
            name='IdentidadGenero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Identidad de Género')),
            ],
            options={
                'verbose_name': 'Identidad de Género',
                'verbose_name_plural': 'Identidades de Género',
            },
        ),
        migrations.CreateModel(
            name='nacionalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nacionalidad')),
            ],
            options={
                'verbose_name': 'Nacionalidad',
                'verbose_name_plural': 'Nacionalidades',
            },
        ),
        migrations.CreateModel(
            name='OpcionSINO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Opciones (CUIT)')),
            ],
            options={
                'verbose_name': 'Opción',
                'verbose_name_plural': 'Opciones (CUIT)',
            },
        ),
        migrations.CreateModel(
            name='RiesgoResidencial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nivel de Riesgo Residencial')),
            ],
            options={
                'verbose_name': 'Riesgo Residencial',
                'verbose_name_plural': 'Riesgos Residenciales',
            },
        ),
        migrations.CreateModel(
            name='TenenciaVivienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Tenencia de la Vivienda')),
            ],
            options={
                'verbose_name': 'Tenencia de Vivienda',
                'verbose_name_plural': 'Tenencias de Vivienda',
            },
        ),
        migrations.CreateModel(
            name='TipoVivienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Tipo de Vivienda')),
            ],
            options={
                'verbose_name': 'Tipo de Vivienda',
                'verbose_name_plural': 'Tipos de Vivienda',
            },
        ),
        migrations.CreateModel(
            name='ViaIngreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Vía de Ingreso del Caso')),
            ],
            options={
                'verbose_name': 'Vía de Ingreso',
                'verbose_name_plural': 'Vías de Ingreso',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_autopercebido', models.CharField(help_text='Campo prioritario y obligatorio.', max_length=255, verbose_name='Nombre Autopercebido')),
                ('iniciales_dni', models.CharField(blank=True, help_text='Para trámites administrativos y archivo (si no tiene cambio registral).', max_length=100, null=True, verbose_name='Iniciales (DNI/Partida)')),
                ('documento_identidad', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Documento de Identidad (DNI/Pasaporte)')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('edad', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Edad')),
                ('direccion_actual_completa', models.TextField(blank=True, null=True, verbose_name='Dirección Actual Completa')),
                ('telefono', models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono')),
                ('correo_electronico', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico')),
                ('fecha_inicio_caso', models.DateField(blank=True, null=True, verbose_name='Fecha de Inicio del Caso')),
                ('profesional_responsable', models.CharField(blank=True, help_text='Nombre del equipo Mocha Celis', max_length=255, null=True, verbose_name='Profesional Responsable')),
                ('estado_dni_rectificado', models.ForeignKey(blank=True, help_text='Mide el acceso al derecho a la identidad.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='datos_personales.estadodni', verbose_name='Estado del DNI rectificado')),
                ('identidad_genero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datos_personales.identidadgenero', verbose_name='Identidad de Género')),
                ('nacionalidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datos_personales.nacionalidad', verbose_name='Nacionalidad')),
                ('posee_cuit_cuil', models.ForeignKey(blank=True, help_text='Necesario para empleo y prestaciones sociales.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personas_cuit_cuil', to='datos_personales.opcionsino', verbose_name='Posee CUIT/CUIL')),
                ('riesgo_residencial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datos_personales.riesgoresidencial', verbose_name='Riesgo Residencial')),
                ('tenencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datos_personales.tenenciavivienda', verbose_name='Tenencia')),
                ('tipo_vivienda', models.ForeignKey(blank=True, help_text='Detallar formas de residencia precaria.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='datos_personales.tipovivienda', verbose_name='Tipo de Vivienda')),
                ('via_ingreso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datos_personales.viaingreso', verbose_name='Vía de Ingreso')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
            },
        ),
    ]
