# Generated by Django 5.2.7 on 2025-10-23 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datos_personales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarreraEducativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Barrera Educativa')),
            ],
            options={
                'verbose_name': 'Barrera Educativa',
                'verbose_name_plural': 'Barreras Educativas',
            },
        ),
        migrations.CreateModel(
            name='EstadoBachilleratoMocha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Estado en Bachillerato Mocha Celis')),
            ],
            options={
                'verbose_name': 'Estado Bachillerato Mocha Celis',
                'verbose_name_plural': 'Estados Bachillerato Mocha Celis',
            },
        ),
        migrations.CreateModel(
            name='EstadoCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Estado del Curso/Capacitación')),
            ],
            options={
                'verbose_name': 'Estado del Curso',
                'verbose_name_plural': 'Estados del Curso',
            },
        ),
        migrations.CreateModel(
            name='NivelEscolaridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nivel de Escolaridad')),
            ],
            options={
                'verbose_name': 'Nivel de Escolaridad',
                'verbose_name_plural': 'Niveles de Escolaridad',
            },
        ),
        migrations.CreateModel(
            name='TipoAcompanamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Tipo de Acompañamiento')),
            ],
            options={
                'verbose_name': 'Tipo de Acompañamiento',
                'verbose_name_plural': 'Tipos de Acompañamiento',
            },
        ),
        migrations.CreateModel(
            name='AcompanamientoEducacion',
            fields=[
                ('persona', models.OneToOneField(help_text='Un registro de educación por cada persona.', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='datos_personales.persona', verbose_name='Persona Acompañada')),
                ('nombre_curso_actual', models.CharField(blank=True, help_text='Ej: Panadería, Oficios Digitales, Asistente Administrativo.', max_length=255, null=True, verbose_name='Nombre del Curso/Capacitación Actual')),
                ('institucion_curso', models.CharField(blank=True, help_text='Permite registrar formaciones externas.', max_length=255, null=True, verbose_name='Institución que dicta el curso')),
                ('fecha_inicio_curso', models.DateField(blank=True, null=True, verbose_name='Fecha de Inicio del Curso')),
                ('areas_interes_futuro', models.TextField(blank=True, help_text='Para planificación de oferta formativa.', verbose_name='Áreas de Interés Futuro')),
                ('barreras_educativas', models.ManyToManyField(blank=True, help_text='Identifica obstáculos que impiden la finalización (Selección múltiple).', to='EducacionFormacion.barreraeducativa', verbose_name='Barreras Educativas identificadas')),
                ('estado_bachillerato_mocha', models.ForeignKey(blank=True, help_text='Mide la participación interna.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='EducacionFormacion.estadobachilleratomocha', verbose_name='Estado en el Bachillerato Mocha Celis')),
                ('estado_curso', models.ForeignKey(blank=True, help_text='Mide el éxito en la finalización.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='EducacionFormacion.estadocurso', verbose_name='Estado del Curso')),
                ('nivel_escolaridad_maximo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='EducacionFormacion.nivelescolaridad', verbose_name='Nivel Máximo Finalizado')),
            ],
            options={
                'verbose_name': 'Acompañamiento - Educación',
                'verbose_name_plural': 'Acompañamiento - Educación y Formación',
            },
        ),
    ]
